name: On push events on `master` build then deploy to Surge

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install then build app
      run: |
        npm ci
        npm run build --if-present
    - name: Deploy to Surge
      run: npx surge dist/ ${{secrets.SURGE_DOMAIN}} --token ${{secrets.SURGE_TOKEN}}
