name: Build & deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies then build application
      run: |
        npm ci
        npm run build --if-present
    - name: Deploy to Surge
      run: npx surge dist/ ${{secrets.SURGE_DOMAIN}}.surge.sh --token ${{secrets.SURGE_TOKEN}}
